### ISSUE TITLE
IRacingSdkConst.cs missing

### ISSUE THREAD

**Issue by thomprl** [mherbold/IRSDKSharperTest#1]
Just going to let you know the IRacingSdkConst.cs is missing from the repo.  I added it from IRSDKSharper

**Comment by Hawgk** [comment]
Update to IRSDKSharper 1.0.15 fixed this for me. Don't update to 1.1.x because namespace "HerboldRacing" will be missing and more issues will pop up.

**Comment by mherbold** [comment]
Thank you for letting me know about this issue - I will update IRSDKSharperTest to make sure it works with the latest version of IRSDKSharper.

**Comment by mherbold** [comment]
Ok - turns out I had already done the updates to the code, I just forgot to push it to GitHub.  This project should be good to go with the latest version of IRSDKSharper now.
